apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: ingress2tier
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host:
    http:
      paths:
      - path: /
      #- path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ingressspring
            port:
              number: 8080
      # - path: /tcc(/|$)(.*)
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: ingressspring
      #       port:
      #         number: 8080
