apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ingress2tier
  name: service-reader
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
