apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ingress2tier
  name: service-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: ingress2tier
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io