replicaCount: 1

namespace: ingress2tier

image:
  repository: ingressreact
  tag: latest
  pullPolicy: Never

service:
  name: frontend
  type: ClusterIP
  port: 80
  targetPort: 80

nodeSelector: {}

tolerations: []

affinity: {} 